import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "@/context/modalContext";
import { Toaster } from "sonner";
import NextTopLoader from "nextjs-toploader";
import { ProductProvider } from "@/context/productContext";
import { CartProvider } from "@/context/cartContext";
import ClientLayout from "@/components/screens/layout/ClientLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Toaster position="bottom-right" richColors duration={2000} />
        <CartProvider>
          <ProductProvider>
            <ModalProvider>
              <NextTopLoader showSpinner={false} color="#EA580C" />
              <ClientLayout>{children}</ClientLayout>
            </ModalProvider>
          </ProductProvider>
        </CartProvider>
      </body>
    </html>
  );
}
