import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarHOC from "@/components/screens/navbar/NavbarHOC";
import FooterHOC from "@/components/screens/footer/FooterHOC";
import { ModalProvider } from "@/context/modalContext";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
         <Toaster position="top-right" richColors />
        <ModalProvider>
          <NavbarHOC />
          {children}
          <FooterHOC />
        </ModalProvider>
      </body>
    </html>
  );
}
